services:
  - type: web
    name: line-bot
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: LINE_TOKEN
        sync: false
      - key: LINE_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
